import { attachLiveAutoHealProof } from '../core/healing-reporter';
import { clickHealing } from '../core/self-healing';
import { expect, test } from './fixtures';
import {
  DEMO_PAUSE_MS,
  demoHealingToast,
  ensureCustomerOnProductsPage,
  formatHealedLocator,
  hideHealingModeIndicator,
  miss,
  showHealingModeIndicator,
} from './demo-toast-helpers';

/** Strategy 3 only: full DOM inventory → synthesized locators (no seed rules). */
const domScanOnlyAutoHeal = {
  enabled: true as const,
  discoverOnly: true as const,
  minConfidence: 70,
  discoveryStrategies: ['dom-scan'] as const,
};

function formatDomScanCandidates(
  candidates: Array<{ strategyName: string; score: number; reason?: string }> | undefined
): string {
  if (!candidates?.length) return '(none)';
  return candidates
    .filter((c) => c.strategyName.startsWith('domscan-'))
    .slice(0, 4)
    .map((c) => `  • ${c.strategyName} (score=${c.score})`)
    .join('\n');
}

test.describe('DOM scan healing showcase (Nova Retail)', () => {
  test.beforeAll(() => {
    delete process.env.AUTO_HEAL_PERSIST;
    delete process.env.AUTO_HEAL_DISCOVER;
    process.env.AUTO_HEAL_DOM_SCAN = '1';
    process.env.AUTO_HEAL_STRATEGIES = 'dom-scan';
  });

  test.afterAll(() => {
    delete process.env.AUTO_HEAL_STRATEGIES;
  });

  test('products add-to-cart — DOM scan discovery + on-screen toasts @dom-scan-healing-showcase', async (
    { page, loginPage: login, retailJourney: journey },
    testInfo
  ) => {
    testInfo.setTimeout(180_000);

    // Phase 1 — silent login (no demo toasts on login screen).
    await login.goto();
    await login.expectLoaded();
    await Promise.all([
      page.waitForURL((url) => !/\/login\/?$/.test(url.pathname), { timeout: 60_000 }),
      login.loginAsCustomer(),
    ]);
    await ensureCustomerOnProductsPage(page);
    await journey.expectProductsReady();

    // Phase 2 — DOM scan healing demo on Products page.
    await showHealingModeIndicator(page, 'dom-scan');
    await demoHealingToast(
      page,
      'dom-scan',
      'On Products page — DOM scan demo',
      `Current URL: ${page.url()}\n\nMode: Strategy 3 — scans visible controls on the page, builds locators from roles/labels/test ids, then validates uniqueness on the live DOM.\n\nSeed rules are OFF for this demo.`,
      'info'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    const brokenLocator = 'button[data-demo-domscan-miss-add="1"]';
    await demoHealingToast(
      page,
      'dom-scan',
      'About to run broken locator',
      `Broken locator: ${brokenLocator}\n\nNext: the framework inventories the page DOM and picks the best matching Add to cart control.`,
      'warn',
      10_000
    );
    await page.waitForTimeout(2_000);

    const addToCart = await clickHealing(page, [miss('add-to-cart-domscan-miss', brokenLocator)], {
      actionType: 'click',
      autoHeal: domScanOnlyAutoHeal,
      timeoutPerStrategyMs: 10_000,
    });

    const selected = addToCart.autoHeal?.selectedCandidate;
    expect(addToCart.autoHeal?.usedAutoGenerated).toBe(true);
    expect(selected?.strategyName).toMatch(/^domscan-/);

    const failedAttempts = addToCart.attempts.filter((a) => !a.ok).length;
    const healedLocator = formatHealedLocator(selected?.query, addToCart.usedStrategy);
    const candidatePreview = formatDomScanCandidates(addToCart.autoHeal?.candidates);

    await demoHealingToast(
      page,
      'dom-scan',
      'Broken step → DOM scan recovery',
      `Broken locator: ${brokenLocator}\nFailed attempts: ${failedAttempts}\n\nThe click succeeded after scanning the page and synthesizing locators.`,
      'warn'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    await demoHealingToast(
      page,
      'dom-scan',
      'Healing details (DOM scan)',
      `Winner: ${selected?.strategyName} (score=${selected?.score})\nHealed locator: ${healedLocator}\nReason: ${selected?.reason ?? 'n/a'}\n\nTop DOM scan candidates:\n${candidatePreview}\n\nPage: ${page.url()}`,
      'ok'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    await journey.gotoCart();
    await expect(page).toHaveURL(/\/app\/cart/, { timeout: 25_000 });

    await attachLiveAutoHealProof(testInfo, [{ title: 'add-to-cart-dom-scan', result: addToCart }]);
    await hideHealingModeIndicator(page);
  });
});
