import type { Page } from '@playwright/test';
import { attachHealingSummary } from '../core/healing-reporter';
import type { LocatorStrategy } from '../core/healing-types';
import { clickHealing } from '../core/self-healing';
import { expect, test } from './fixtures';
import {
  DEMO_PAUSE_MS,
  demoHealingToast,
  ensureCustomerOnProductsPage,
  formatHealedLocator,
  hideHealingModeIndicator,
  miss,
  showHealingModeIndicator,
} from './demo-toast-helpers';

/** Static healing only: ordered fallback strategies. Auto-heal discovery is disabled. */
const staticOnly = { enabled: false as const };

const addToCartStaticChain: LocatorStrategy[] = [
  {
    name: 'role-button-Add-to-cart',
    resolve: (p: Page) => p.getByRole('button', { name: /add to cart/i }).first(),
  },
  {
    name: 'role-button-Add-item',
    resolve: (p: Page) => p.getByRole('button', { name: /add item/i }).first(),
  },
  {
    name: 'card-primary-button',
    resolve: (p: Page) => p.locator('.rw-card-actions .rw-btn-primary').first(),
  },
];

test.describe('Static healing showcase (ordered strategies)', () => {
  test('products add-to-cart — static fallback chain @static-healing-showcase', async (
    { page, loginPage: login, retailJourney: journey },
    testInfo
  ) => {
    testInfo.setTimeout(180_000);

    // Phase 1 — silent login (no demo toasts on login screen).
    await login.goto();
    await login.expectLoaded();
    await Promise.all([
      page.waitForURL((url) => !/\/login\/?$/.test(url.pathname), { timeout: 60_000 }),
      login.loginAsCustomer(),
    ]);
    await ensureCustomerOnProductsPage(page);
    await journey.expectProductsReady();

    // Phase 2 — static healing demo on Products page.
    await showHealingModeIndicator(page, 'static');
    await demoHealingToast(
      page,
      'static',
      'On Products page — static healing demo',
      `Current URL: ${page.url()}\n\nMode: ordered fallback strategies (auto-discovery OFF)\n\nYou will see:\n- Broken Add to cart locator\n- Next predefined strategy succeeds`,
      'info'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    const brokenLocator = 'button[data-demo-static-miss-add="1"]';
    await demoHealingToast(
      page,
      'static',
      'About to run broken locator',
      `Broken locator: ${brokenLocator}\nWatch the product card — the next static strategy in the chain will click Add to cart.`,
      'warn',
      10_000
    );
    await page.waitForTimeout(2_000);

    const addToCart = await clickHealing(
      page,
      [miss('broken-primary', brokenLocator), ...addToCartStaticChain],
      { actionType: 'click', autoHeal: staticOnly, timeoutPerStrategyMs: 8_000 }
    );

    expect(addToCart.autoHeal?.usedAutoGenerated).toBeFalsy();

    await demoHealingToast(
      page,
      'static',
      'Broken step → static fallback',
      `Broken locator: ${brokenLocator}\nFailed attempts: ${addToCart.attempts.filter((a) => !a.ok).length}\n\nRecovery used a predefined strategy (not auto-discovery).`,
      'warn'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    const healedLocator = formatHealedLocator(undefined, addToCart.usedStrategy);
    await demoHealingToast(
      page,
      'static',
      'Healing details (static)',
      `Static strategy used: ${addToCart.usedStrategy}\nHealed locator: ${healedLocator}\nPage: ${page.url()}`,
      'ok'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    await journey.gotoCart();
    await expect(page).toHaveURL(/\/app\/cart/, { timeout: 25_000 });

    await attachHealingSummary(testInfo, 'add-to-cart-static', addToCart);
    await hideHealingModeIndicator(page);
  });
});
