import { attachHealingSummary } from '../core/healing-reporter';
import { fillHealing } from '../core/self-healing';
import { expect, test } from './fixtures';
import { CUSTOMER_EMAIL } from './traceability/_helpers';
import {
  DEMO_PAUSE_MS,
  demoToast,
  formatHealedLocator,
  miss,
} from './demo-toast-helpers';

/** Static healing only: ordered fallback strategies. Auto-heal discovery is disabled. */
const staticOnly = { enabled: false as const };

test.describe('Static healing showcase (ordered strategies)', () => {
  test('login email — static fallback chain @static-healing-showcase', async ({ page, loginPage: login }, testInfo) => {
    testInfo.setTimeout(120_000);
    await login.goto();

    await demoToast(
      page,
      'Static healing (ordered strategies)',
      'Mode:\n- Uses predefined fallback locators in order\n- Auto-heal discovery is OFF\n\nWhat you will see:\n- First locator fails\n- Next strategy in the chain succeeds',
      'info'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    const brokenLocator = 'input[data-demo-static-miss="1"]';
    const email = await fillHealing(
      page,
      [
        miss('broken-primary', brokenLocator),
        {
          name: 'getByLabel-Email',
          resolve: (p) => p.getByLabel(/email/i),
        },
        {
          name: 'placeholder-email',
          resolve: (p) => p.locator('input[type="email"], input[name*="email" i], input[id*="email" i]').first(),
        },
      ],
      CUSTOMER_EMAIL,
      { actionType: 'fill', autoHeal: staticOnly, timeoutPerStrategyMs: 6_000 }
    );

    expect(email.autoHeal?.usedAutoGenerated).toBeFalsy();

    await demoToast(
      page,
      'Broken test step detected',
      `Observed issue:\n- Primary locator did not match the DOM\n- Broken locator: ${brokenLocator}\n\nAction:\n- Trying next predefined strategy in the static chain`,
      'warn'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    const healedLocator = formatHealedLocator(undefined, email.usedStrategy);
    await demoToast(
      page,
      'Healing details (static)',
      `Recovery result:\n- Static strategy used: ${email.usedStrategy}\n- Healed locator: ${healedLocator}\n- No auto-generated locator was used`,
      'ok'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    await attachHealingSummary(testInfo, 'login-email-static', email);
    await expect(page).toHaveURL(/\/login/);
  });
});
