import type { MaintenanceHealingSnapshot } from 'autonomous-agent-contracts';
import type { GeneratedLocatorCandidate } from 'ai-healing-sdk';
import { toHealingSnapshot } from './locator-types';

export function healingSnapshotFromResult(result: {
  autoHeal?: { usedAutoGenerated?: boolean; selectedCandidate?: GeneratedLocatorCandidate };
}): MaintenanceHealingSnapshot | undefined {
  if (!result.autoHeal?.usedAutoGenerated || !result.autoHeal.selectedCandidate) return undefined;
  return toHealingSnapshot(result.autoHeal.selectedCandidate);
}
