import type { Locator, Page } from '@playwright/test';

/** One way to resolve a locator; used in ordered fallback chains. */
export type LocatorStrategy = {
  name: string;
  resolve: (page: Page) => Locator;
  source?: LocatorSource;
};

export type LocatorSource = {
  filePath?: string;
  methodName?: string;
  actionKey?: string;
};

export type GeneratedLocatorQuery =
  | {
      type: 'css';
      value: string;
    }
  | {
      type: 'role';
      role: Parameters<Page['getByRole']>[0];
      name: string;
    };

export type GeneratedLocatorCandidate = {
  strategyName: string;
  query: GeneratedLocatorQuery;
  score: number;
  reason: string;
};

export type HealingAttempt = {
  strategy: string;
  ok: boolean;
  error?: string;
  source?: LocatorSource;
  autogenerated?: boolean;
  score?: number;
  reason?: string;
  query?: GeneratedLocatorQuery;
};

export type HealingResult<T> = {
  value: T;
  usedStrategy: string;
  attempts: HealingAttempt[];
  autoHeal?: {
    usedAutoGenerated: boolean;
    selectedCandidate?: GeneratedLocatorCandidate;
    candidates?: GeneratedLocatorCandidate[];
    persisted?: {
      filePath: string;
      methodName: string;
      strategyName: string;
    };
  };
};
