import type { Locator, Page } from '@playwright/test';
import { discoverAutoHealingCandidates, generatedQueryKey, generatedQueryToLocatorFactory } from './auto-heal-discovery';
import { recordHistoryOutcome } from './auto-heal-history';
import { persistGeneratedLocator } from './auto-heal-persistence';
import type {
  GeneratedLocatorCandidate,
  HealingAttempt,
  HealingResult,
  LocatorStrategy,
} from './healing-types';

const DEFAULT_PER_STRATEGY_MS = 5_000;
const DEFAULT_MIN_CONFIDENCE = 70;

function recordFailure(
  attempts: HealingAttempt[],
  name: string,
  error: unknown,
  source?: LocatorStrategy['source']
): void {
  attempts.push({
    strategy: name,
    ok: false,
    error: error instanceof Error ? error.message : String(error),
    source,
  });
}

type ActionType = 'click' | 'fill' | 'visible';

type AutoHealPersistTarget = {
  filePath: string;
  methodName: string;
};

type AutoHealOptions = {
  enabled?: boolean;
  discoverOnly?: boolean;
  minConfidence?: number;
  persistTarget?: AutoHealPersistTarget;
  validationPasses?: number;
  discoverer?: (args: {
    page: Page;
    actionType: ActionType;
    attempts: HealingAttempt[];
  }) => Promise<GeneratedLocatorCandidate[]>;
};

type HealingOptions = {
  timeoutPerStrategyMs?: number;
  actionType?: ActionType;
  autoHeal?: AutoHealOptions;
};

function envTruthy(value: string | undefined): boolean {
  return value === '1' || value === 'true';
}

function resolveAutoHealConfig(options?: HealingOptions): AutoHealOptions {
  const auto = options?.autoHeal ?? {};
  const enabled = auto.enabled ?? envTruthy(process.env.AUTO_HEAL_DISCOVER);
  const discoverOnly = auto.discoverOnly ?? !envTruthy(process.env.AUTO_HEAL_PERSIST);
  const minConfidence = auto.minConfidence ?? Number(process.env.AUTO_HEAL_MIN_CONFIDENCE || DEFAULT_MIN_CONFIDENCE);
  const validationPasses = auto.validationPasses ?? 2;
  return {
    ...auto,
    enabled,
    discoverOnly,
    minConfidence: Number.isFinite(minConfidence) ? minConfidence : DEFAULT_MIN_CONFIDENCE,
    validationPasses,
  };
}

async function scoreCandidateViability(page: Page, candidate: GeneratedLocatorCandidate): Promise<number> {
  try {
    const loc = generatedQueryToLocatorFactory(candidate.query)(page).first();
    const count = await loc.count();
    if (count < 1) return -1000;
    return count === 1 ? 10 : Math.max(0, 6 - count);
  } catch {
    return -1000;
  }
}

/**
 * Runs an action against locators from each strategy until one succeeds.
 * Order matters: stable selectors first, fallbacks after.
 */
export async function withHealingPage<T>(
  page: Page,
  strategies: LocatorStrategy[],
  action: (locator: Locator) => Promise<T>,
  options?: HealingOptions
): Promise<HealingResult<T>> {
  const attempts: HealingAttempt[] = [];
  let lastError: unknown;
  const actionType: ActionType = options?.actionType ?? 'visible';
  const autoConfig = resolveAutoHealConfig(options);

  for (const s of strategies) {
    const locator = s.resolve(page);
    try {
      const value = await action(locator);
      attempts.push({ strategy: s.name, ok: true, source: s.source });
      return { value, usedStrategy: s.name, attempts };
    } catch (e) {
      lastError = e;
      recordFailure(attempts, s.name, e, s.source);
    }
  }

  if (autoConfig.enabled) {
    const discover = autoConfig.discoverer ?? ((args: { page: Page; actionType: ActionType; attempts: HealingAttempt[] }) =>
      discoverAutoHealingCandidates(args));
    const generated = await discover({ page, actionType, attempts });
    const candidates: GeneratedLocatorCandidate[] = [];
    for (const c of generated) {
      const bonus = await scoreCandidateViability(page, c);
      if (bonus < -100) continue;
      candidates.push({ ...c, score: c.score + bonus });
    }
    candidates.sort((a, b) => b.score - a.score);

    for (const candidate of candidates) {
      const locator = generatedQueryToLocatorFactory(candidate.query)(page);
      try {
        const value = await action(locator);
        attempts.push({
          strategy: candidate.strategyName,
          ok: true,
          autogenerated: true,
          score: candidate.score,
          reason: candidate.reason,
          query: candidate.query,
        });
        recordHistoryOutcome(page.url(), actionType, generatedQueryKey(candidate.query), true);

        const result: HealingResult<T> = {
          value,
          usedStrategy: candidate.strategyName,
          attempts,
          autoHeal: {
            usedAutoGenerated: true,
            selectedCandidate: candidate,
            candidates,
          },
        };

        const canPersist =
          !autoConfig.discoverOnly &&
          Boolean(
            autoConfig.persistTarget ||
              attempts.find((a) => a.source?.filePath && a.source?.methodName)?.source
          ) &&
          candidate.score >= (autoConfig.minConfidence ?? DEFAULT_MIN_CONFIDENCE);
        const inferredTarget = attempts.find((a) => a.source?.filePath && a.source?.methodName)?.source;
        if (canPersist && (autoConfig.persistTarget || inferredTarget)) {
          const persisted = persistGeneratedLocator({
            target:
              autoConfig.persistTarget ??
              ({
                filePath: inferredTarget!.filePath!,
                methodName: inferredTarget!.methodName!,
              }),
            candidate,
            minConfidence: autoConfig.minConfidence ?? DEFAULT_MIN_CONFIDENCE,
            validationPasses: autoConfig.validationPasses ?? 2,
          });
          if (persisted.ok) {
            result.autoHeal = {
              usedAutoGenerated: true,
              selectedCandidate: candidate,
              candidates,
              persisted: {
                filePath: persisted.filePath,
                methodName: persisted.methodName,
                strategyName: persisted.strategyName,
              },
            };
          }
        }
        return result;
      } catch (e) {
        lastError = e;
        attempts.push({
          strategy: candidate.strategyName,
          ok: false,
          error: e instanceof Error ? e.message : String(e),
          autogenerated: true,
          score: candidate.score,
          reason: candidate.reason,
          query: candidate.query,
        });
        recordHistoryOutcome(page.url(), actionType, generatedQueryKey(candidate.query), false);
      }
    }
  }

  const summary = attempts.map((a) => `${a.strategy}: ${a.error ?? 'unknown'}`).join('\n');
  throw new Error(
    `Self-healing exhausted ${strategies.length} strategies.\n${summary}`,
    { cause: lastError }
  );
}

export async function clickHealing(
  page: Page,
  strategies: LocatorStrategy[],
  options?: HealingOptions & { force?: boolean }
): Promise<HealingResult<void>> {
  const timeout = options?.timeoutPerStrategyMs ?? DEFAULT_PER_STRATEGY_MS;
  return withHealingPage(
    page,
    strategies,
    async (loc) => {
      await loc.first().click({ timeout, force: options?.force });
    },
    { ...options, actionType: 'click' }
  );
}

export async function fillHealing(
  page: Page,
  strategies: LocatorStrategy[],
  value: string,
  options?: HealingOptions
): Promise<HealingResult<void>> {
  const timeout = options?.timeoutPerStrategyMs ?? DEFAULT_PER_STRATEGY_MS;
  return withHealingPage(
    page,
    strategies,
    async (loc) => {
      await loc.first().fill(value, { timeout });
    },
    { ...options, actionType: 'fill' }
  );
}

export async function expectVisibleHealing(
  page: Page,
  strategies: LocatorStrategy[],
  options?: HealingOptions
): Promise<HealingResult<void>> {
  const timeout = options?.timeoutPerStrategyMs ?? DEFAULT_PER_STRATEGY_MS;
  return withHealingPage(
    page,
    strategies,
    async (loc) => {
      await loc.first().waitFor({ state: 'visible', timeout });
    },
    { ...options, actionType: 'visible' }
  );
}
