import type { Page } from '@playwright/test';
import type { AutonomousAction, AutonomousPlannedStep, MaintenanceHealingSnapshot } from 'autonomous-agent-contracts';
import { clickHealing, expectVisibleHealing, fillHealing } from '../retry/retry-orchestrator';
import { healingSnapshotFromResult } from '../maintenance/healing-capture';
import { assertDomainAllowed, strategiesForHeading, strategiesForHint, strategiesForText } from './strategies-for-hint';
import {
  destructiveActionBlockedReason,
  isDestructiveActionAllowed,
} from './destructive-action-guard';

export type ExecuteStepResult = {
  ok: boolean;
  error?: string;
  healed?: boolean;
  usedStrategy?: string;
  healingSnapshot?: MaintenanceHealingSnapshot;
  destructiveBlocked?: boolean;
};

export type ExecuteStepOptions = {
  healOnFailure?: boolean;
  timeoutPerActionMs?: number;
  allowedDomains?: string[];
  goal?: string;
  allowDestructiveActions?: boolean;
};

async function runFill(page: Page, action: Extract<AutonomousAction, { type: 'fill' }>, options: ExecuteStepOptions): Promise<ExecuteStepResult> {
  const strategies = strategiesForHint(action.targetHint, 'fill');
  const result = await fillHealing(page, strategies, action.value, {
    timeoutPerStrategyMs: options.timeoutPerActionMs ?? 8_000,
    autoHeal: { enabled: options.healOnFailure !== false, agentMode: 'agentic', discoverOnly: true },
  });
  return {
    ok: true,
    healed: Boolean(result.autoHeal?.usedAutoGenerated),
    usedStrategy: result.usedStrategy,
    healingSnapshot: healingSnapshotFromResult(result),
  };
}

async function runClick(page: Page, action: Extract<AutonomousAction, { type: 'click' }>, options: ExecuteStepOptions): Promise<ExecuteStepResult> {
  const strategies = strategiesForHint(action.targetHint, 'click');
  const result = await clickHealing(page, strategies, {
    timeoutPerStrategyMs: options.timeoutPerActionMs ?? 8_000,
    autoHeal: { enabled: options.healOnFailure !== false, agentMode: 'agentic', discoverOnly: true },
  });
  await page.waitForLoadState('domcontentloaded').catch(() => undefined);
  return {
    ok: true,
    healed: Boolean(result.autoHeal?.usedAutoGenerated),
    usedStrategy: result.usedStrategy,
    healingSnapshot: healingSnapshotFromResult(result),
  };
}

async function runAssertUrl(
  page: Page,
  action: Extract<AutonomousAction, { type: 'assert_url' }>,
  options: ExecuteStepOptions = {}
): Promise<ExecuteStepResult> {
  const timeout = options.timeoutPerActionMs ?? 15_000;

  if (action.mustNotMatch) {
    const pattern = new RegExp(action.mustNotMatch);
    try {
      await page.waitForURL((url) => !pattern.test(url.pathname), { timeout });
    } catch {
      return {
        ok: false,
        error: `URL ${page.url()} still matches forbidden pattern ${action.mustNotMatch} after ${timeout}ms`,
      };
    }
  }

  if (action.mustMatch) {
    const pattern = new RegExp(action.mustMatch);
    try {
      await page.waitForURL((url) => pattern.test(url.pathname), { timeout });
    } catch {
      return {
        ok: false,
        error: `URL ${page.url()} does not match required pattern ${action.mustMatch} after ${timeout}ms`,
      };
    }
  }

  return { ok: true, usedStrategy: 'assert_url' };
}

async function runAssertVisible(page: Page, action: Extract<AutonomousAction, { type: 'assert_visible' }>, options: ExecuteStepOptions): Promise<ExecuteStepResult> {
  const strategies = strategiesForHint(action.targetHint, 'visible');
  const result = await expectVisibleHealing(page, strategies, {
    timeoutPerStrategyMs: options.timeoutPerActionMs ?? 8_000,
    autoHeal: { enabled: options.healOnFailure !== false, agentMode: 'agentic', discoverOnly: true },
  });
  return {
    ok: true,
    healed: Boolean(result.autoHeal?.usedAutoGenerated),
    usedStrategy: result.usedStrategy,
  };
}

async function runAssertHeading(
  page: Page,
  action: Extract<AutonomousAction, { type: 'assert_heading' }>,
  options: ExecuteStepOptions
): Promise<ExecuteStepResult> {
  const strategies = strategiesForHeading(action.textHint);
  try {
    const result = await expectVisibleHealing(page, strategies, {
      timeoutPerStrategyMs: options.timeoutPerActionMs ?? 12_000,
      autoHeal: { enabled: options.healOnFailure !== false, agentMode: 'agentic', discoverOnly: true },
    });
    return {
      ok: true,
      healed: Boolean(result.autoHeal?.usedAutoGenerated),
      usedStrategy: result.usedStrategy,
      healingSnapshot: healingSnapshotFromResult(result),
    };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

async function runAssertText(
  page: Page,
  action: Extract<AutonomousAction, { type: 'assert_text' }>,
  options: ExecuteStepOptions
): Promise<ExecuteStepResult> {
  const parts = action.textHint.split('|').map((p) => p.trim()).filter(Boolean);
  const pattern = parts.length > 1 ? new RegExp(parts.join('|'), 'i') : new RegExp(action.textHint, 'i');
  const timeout = options.timeoutPerActionMs ?? 12_000;
  const started = Date.now();

  while (Date.now() - started < timeout) {
    const text = await page.locator('body').innerText().catch(() => '');
    if (pattern.test(text)) {
      return { ok: true, usedStrategy: 'assert_text' };
    }
    await page.waitForTimeout(300);
  }

  // Fallback: try visible text locators via healing
  try {
    const strategies = strategiesForText(action.textHint);
    const result = await expectVisibleHealing(page, strategies, {
      timeoutPerStrategyMs: Math.min(8_000, timeout),
      autoHeal: { enabled: options.healOnFailure !== false, agentMode: 'agentic', discoverOnly: true },
    });
    return {
      ok: true,
      healed: Boolean(result.autoHeal?.usedAutoGenerated),
      usedStrategy: result.usedStrategy,
      healingSnapshot: healingSnapshotFromResult(result),
    };
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : `Body text does not match ${action.textHint}`,
    };
  }
}

export async function executeAutonomousStep(
  page: Page,
  step: AutonomousPlannedStep,
  options: ExecuteStepOptions = {}
): Promise<ExecuteStepResult> {
  const action = step.action;

  if (
    options.goal &&
    !isDestructiveActionAllowed({
      goal: options.goal,
      action,
      allowDestructiveActions: options.allowDestructiveActions,
    })
  ) {
    return {
      ok: false,
      error: destructiveActionBlockedReason(action),
      destructiveBlocked: true,
      usedStrategy: 'destructive-guard',
    };
  }

  if (action.type === 'navigate') {
    await page.goto(action.url, { waitUntil: 'domcontentloaded' });
    assertDomainAllowed(page, options.allowedDomains);
    return { ok: true, usedStrategy: 'navigate' };
  }

  if (action.type === 'wait') {
    await page.waitForTimeout(action.ms);
    return { ok: true, usedStrategy: 'wait' };
  }

  if (action.type === 'fill') {
    try {
      return await runFill(page, action, options);
    } catch (e) {
      return { ok: false, error: e instanceof Error ? e.message : String(e) };
    }
  }

  if (action.type === 'click') {
    try {
      return await runClick(page, action, options);
    } catch (e) {
      return { ok: false, error: e instanceof Error ? e.message : String(e) };
    }
  }

  if (action.type === 'assert_url') {
    return runAssertUrl(page, action, options);
  }

  if (action.type === 'assert_visible') {
    try {
      return await runAssertVisible(page, action, options);
    } catch (e) {
      return { ok: false, error: e instanceof Error ? e.message : String(e) };
    }
  }

  if (action.type === 'assert_heading') {
    return runAssertHeading(page, action, options);
  }

  if (action.type === 'assert_text') {
    return runAssertText(page, action, options);
  }

  if (action.type === 'complete') {
    return { ok: true, usedStrategy: 'complete' };
  }

  if (action.type === 'fail') {
    return { ok: false, error: action.reason };
  }

  return { ok: false, error: `Unsupported action type` };
}
